# Generated by Django 5.1.3 on 2024-12-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование'),
        ),
    ]
