# Generated by Django 5.1.3 on 2024-12-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='tag.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='tag.tag', verbose_name='Теги'),
        ),
    ]
