# Generated by Django 5.1.3 on 2024-12-07 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_created_at_alter_comment_updated_at'),
        ('publication', '0004_alter_article_author_alter_video_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publication.publication', verbose_name='Публикация'),
        ),
    ]
